### ISSUE TITLE
请问如何使用？我想下载半次元的无水印图片

### ISSUE THREAD

**Issue by gimgoo** [slybootslion/my-crawler#1]
我想下载半次元的无水印图片，除了执行npm run serve有网页外，其他都没有说可以访问网页的。但是npm run serve执行后的网页输入链接，提示服务器错误。

**Comment by slybootslion** [comment]
没想到自己写着玩的小工具会有人来使用，我更新的readme，请查看。
还真的有点好奇这个会有多少人来用。

**Comment by sushengbuhuo** [comment]
有在线地址吗 @slybootslion

**Comment by slybootslion** [comment]
@sushengbuhuo 更新了在线地址

**Comment by slybootslion** [comment]
这个issues我关了，有什么问题建立新的issue。
